In [144]:
import sys
import pandas as pd
import seaborn

In [ ]:
vax_exemptions = pd.read_csv('school_vaccine_exemptions.csv')
elementary_directory = pd.read_csv('elementary_directory.csv', quotechar='"') 
#https://schools.utah.gov/schoolsdirectory

vax_exemptions = vax_exemptions.rename(columns={vax_exemptions.columns[0]: 'School'})
# df = df.dropna(how='all')
vax_exemptions = vax_exemptions.dropna(how = 'all') # this didn't work lol

In [163]:
vax_exemptions.head()

,School,City,Adequately immunized %,Exempt %,Conditionally enrolled %,Extended conditionally enrolled %,Out of compliance %
1,river rock school,lehi,89.7,10.3,0.0,0.0,0.0
2,springside school,saratoga springs,82.9,13.7,0.9,0.9,1.7
3,american preparatory academy accelerated school,west valley city,94.2,3.5,0.0,2.3,0.0
4,american preparatory academy,draper,92.0,7.0,1.0,0.0,0.0
5,american preparatory academy salem,salem,74.6,25.4,0.0,0.0,0.0

In [146]:
elementary_directory

,District/LEA,District #,School,School #,Private,Charter,T-I Prev.,T-I Curr.,Grades,Address,...,Link,Stats,Phone,Fax,Chartered By,Opened,Closed,Principal/Director,Principal Name,Principal Email
0,A to Z Building Blocks,AZ,A to Z Building Blocks American Fork on 100 East,901,Private,NaN,NaN,NaN,Pre - 6,195 North 100 East,...,atozbuildingblocks.com,NaN,801-754-6704,NaN,NaN,2021,NaN,Administrator,NaN,Jody@atozbuildingblocks.com
1,A to Z Building Blocks,AZ,A to Z Building Blocks American Fork on 300 East,902,Private,NaN,NaN,NaN,Pre - 6,153 North 300 East,...,atozbuildingblocks.com,NaN,801-754-6704,NaN,NaN,2021,NaN,Coordinator,NaN,Jody@atozbuildingblocks.com
2,A to Z Building Blocks,AZ,A to Z Building Blocks Draper,903,Private,NaN,NaN,NaN,Pre - 6,978 E Draper Parkway,...,atozbuildingblocks.com,NaN,801-754-6704,NaN,NaN,2021,NaN,Administrator,NaN,Jody@atozbuildingblocks.com
3,A to Z Building Blocks,AZ,A to Z Building Blocks on Ranches Parkway,904,Private,NaN,NaN,NaN,Pre - 6,3563 Ranches Parkway,...,atozbuildingblocks.com,NaN,801-754-6704,NaN,NaN,2021,NaN,Administrator,NaN,jody@atozbuildingblocks.com
4,A to Z Building Blocks,AZ,A to Z Building Blocks Orem,905,Private,NaN,NaN,NaN,Pre - 6,670 W 400 N,...,atozbuildingblocks.com,NaN,801-754-6704,NaN,NaN,2021,NaN,Administrator,NaN,Jody@atozbuildingblocks.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Weber District,35,Weber Online K-6,199,Public,NaN,NaN,NaN,K - 6,5320 Adams Avenue Parkway,...,http://weberonline.wsd.net,https://datagateway.schools.utah.gov/Schools/3...,801-476-7877,801-476-7894,NaN,2011,NaN,Administrator,Justin Skeen,jskeen@wsd.net
696,Weber District,35,West Haven School,162,Public,NaN,NaN,NaN,K - 6,4385 S 3900 W,...,http://www.whe.weber.k12.ut.us,https://datagateway.schools.utah.gov/Schools/3...,801-452-4960,801-452-4979,NaN,2004,NaN,Principal,Courtney Geisler,cogeisler@wsd.net
697,Weber District,35,West Weber School,164,Public,NaN,NaN,NaN,K - 6,4178 West 900 South,...,http://www.wsdpc.org,https://datagateway.schools.utah.gov/Schools/3...,801-452-4280,801-452-4299,NaN,1928,NaN,Principal,Daryl Fluckiger,dafluckiger1@wsd.net
698,Weber State University Charter Academy,7I,Weber State University Charter Academy,100,Public,Charter,NaN,NaN,K - 3,"1351 Edvalson Street Department 1305, Weber St...",...,weber.edu/charteracademy/,https://datagateway.schools.utah.gov/Schools/7...,801-626-6343,801-626-7427,University or College,2013,NaN,Director,Lindsay Baird,lindsaybaird@weber.edu
699,Weilenmann School of Discovery,6G,Weilenmann School of Discovery,100,Public,Charter,NaN,NaN,K - 8,4199 W KILBY ROAD,...,http://wsdpc.org/,https://datagateway.schools.utah.gov/Schools/6...,435-575-5411,435-575-5412,State Charter School Board (SCSB),2010,NaN,Director,Scott Stewart,scottstewart@wsdpc.org

In [147]:
def classify_school(row):
    if row['Private'] == 'Private':
        return 'Private'
    elif row['Charter'] == 'Charter':
        return 'Charter'
    else: 
        return 'Public'
    

elementary_directory['school_type'] = elementary_directory.apply(classify_school, axis=1)

print(elementary_directory.loc[elementary_directory['school_type'] == 'Private', 'School'])

elementary_directory = elementary_directory.drop(columns = ['Private', 'Charter', 'T-I Prev.', 'T-I Curr.', 'School #', 'District #', 'Link', 'Stats', 'Phone', 'Fax', 'Chartered By', 'Opened', 'Closed', 'Principal/Director', 'Principal Name', 'Principal Email'])

0      A to Z Building Blocks American Fork on 100 East
1      A to Z Building Blocks American Fork on 300 East
2                         A to Z Building Blocks Draper
3             A to Z Building Blocks on Ranches Parkway
4                           A to Z Building Blocks Orem
                             ...
617                                   Redeemer Lutheran
618                             Trinity Lutheran School
621                           Valor Preparatory Academy
627                            Wasatch Christian School
663                                    Waterford School
Name: School, Length: 79, dtype: str

In [ ]:
def normalize_str(s): # hoping for more schools in common, but this actually didn't really work 
    return s.str.strip().str.lower()

for col in ['School', 'City']:
    elementary_directory[col] = normalize_str(elementary_directory[col])

In [150]:
elementary_directory

,District/LEA,School,Grades,Address,City,Zip,Map,school_type
0,A to Z Building Blocks,a to z building blocks american fork on 100 east,Pre - 6,195 North 100 East,american fork,84003,"geo:40.38,-111.796",Private
1,A to Z Building Blocks,a to z building blocks american fork on 300 east,Pre - 6,153 North 300 East,american fork,84003,"geo:40.38,-111.791",Private
2,A to Z Building Blocks,a to z building blocks draper,Pre - 6,978 E Draper Parkway,draper,84020,"geo:40.526,-111.864",Private
3,A to Z Building Blocks,a to z building blocks on ranches parkway,Pre - 6,3563 Ranches Parkway,eagle mountain,84005,"geo:40.361,-111.975",Private
4,A to Z Building Blocks,a to z building blocks orem,Pre - 6,670 W 400 N,orem,84057,"geo:40.305,-111.712",Private
...,...,...,...,...,...,...,...,...
695,Weber District,weber online k-6,K - 6,5320 Adams Avenue Parkway,ogden,84405,"geo:41.167085,-111.967868",Public
696,Weber District,west haven school,K - 6,4385 S 3900 W,west haven,84401,"geo:41.184443,-112.076201",Public
697,Weber District,west weber school,K - 6,4178 West 900 South,ogden,84404,"geo:41.2502,-112.008059",Public
698,Weber State University Charter Academy,weber state university charter academy,K - 3,"1351 Edvalson Street Department 1305, Weber St...",ogden,84408,"geo:41.1933683,-111.946632",Charter
699,Weilenmann School of Discovery,weilenmann school of discovery,K - 8,4199 W KILBY ROAD,park city,84098,"geo:40.751592,-111.593779",Charter

In [151]:
vax_exemptions

,School,City,Adequately immunized %,Exempt %,Conditionally enrolled %,Extended conditionally enrolled %,Out of compliance %
1,River Rock School,Lehi,89.7,10.3,0.0,0.0,0.0
2,Springside School,Saratoga Springs,82.9,13.7,0.9,0.9,1.7
3,American Preparatory Academy Accelerated School,West Valley City,94.2,3.5,0.0,2.3,0.0
4,American Preparatory Academy,Draper,92.0,7.0,1.0,0.0,0.0
5,American Preparatory Academy Salem,Salem,74.6,25.4,0.0,0.0,0.0
...,...,...,...,...,...,...,...
692,Island View School,West Point,91.0,7.2,0.0,0.9,0.9
694,Utah Peak Academy,Junction,50.0,45.0,2.5,0.0,2.5
695,Wallace Stegner Academy Kearns,West Valley City,95.9,4.1,0.0,0.0,0.0
696,Haven Bay,West Haven,89.8,8.5,0.0,1.7,0.0
697,American Principles Academy,Cedar,54.2,37.5,0.0,8.3,0.0

In [ ]:
for col in ['School', 'City']:
    vax_exemptions[col] = normalize_str(vax_exemptions[col])

In [153]:
vax_exemptions

,School,City,Adequately immunized %,Exempt %,Conditionally enrolled %,Extended conditionally enrolled %,Out of compliance %
1,river rock school,lehi,89.7,10.3,0.0,0.0,0.0
2,springside school,saratoga springs,82.9,13.7,0.9,0.9,1.7
3,american preparatory academy accelerated school,west valley city,94.2,3.5,0.0,2.3,0.0
4,american preparatory academy,draper,92.0,7.0,1.0,0.0,0.0
5,american preparatory academy salem,salem,74.6,25.4,0.0,0.0,0.0
...,...,...,...,...,...,...,...
692,island view school,west point,91.0,7.2,0.0,0.9,0.9
694,utah peak academy,junction,50.0,45.0,2.5,0.0,2.5
695,wallace stegner academy kearns,west valley city,95.9,4.1,0.0,0.0,0.0
696,haven bay,west haven,89.8,8.5,0.0,1.7,0.0
697,american principles academy,cedar,54.2,37.5,0.0,8.3,0.0

In [ ]:
merged_df = pd.merge(vax_exemptions, elementary_directory, on=['School', 'City'], how='inner')

In [155]:
merged_df

,School,City,Adequately immunized %,Exempt %,Conditionally enrolled %,Extended conditionally enrolled %,Out of compliance %,District/LEA,Grades,Address,Zip,Map,school_type
0,river rock school,lehi,89.7,10.3,0.0,0.0,0.0,Alpine District,Pre - 6,520 North 1700 West,84043,"geo:40.3937097,-111.8764976",Public
1,springside school,saratoga springs,82.9,13.7,0.9,0.9,1.7,Alpine District,Pre - 6,694 South Highpoint Drive,84045,"geo:40.3494704,-111.9152738",Public
2,american preparatory academy,draper,92.0,7.0,1.0,0.0,0.0,American Preparatory Academy,K - 6,12892 S PONY EXPRESS RD,84020,"geo:40.517489,-111.891825",Charter
3,ascent academies of utah lehi,lehi,87.0,13.0,0.0,0.0,0.0,Ascent Academies of Utah,K - 9,2199 W 900 N,84043,"geo:40.3986691,-111.8870765",Charter
4,birch creek school,smithfield,93.0,5.3,0.9,0.0,0.9,Cache District,Pre - 6,675 W 220 N,84335,"geo:41.842084,-111.852014",Public
...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,silver lake elementary,eagle mountain,84.5,15.5,0.0,0.0,0.0,Alpine District,Pre - 6,5069 Golden Eagle Road,84005,"geo:40.350111,-111.96156",Public
514,sunburst school,layton,90.2,7.3,0.0,1.6,0.8,Davis District,Pre - 6,2504 W Sunburst Drive,84041,"geo:41.06016,-112.01109",Public
515,trailside elementary,vineyard,86.1,7.9,0.0,6.0,0.0,Alpine District,Pre - 6,452 N Vineyard Loop Road,84058,"geo:40.30451,-111.74758",Public
516,twenty wells elementary,grantsville,94.0,6.0,0.0,0.0,0.0,Tooele District,Pre - 6,636 E Nygreen,84029,"geo:40.5783,-112.43632",Public
517,utah peak academy,junction,50.0,45.0,2.5,0.0,2.5,Piute District,K - 12,PO Box 69,84740,"geo:38.245546,-112.221783",Public

In [ ]:
immunizations = merged_df.drop_duplicates(subset = ['School', 'City'])
immunizations = immunizations.reset_index(drop = True)

In [158]:
immunizations

,School,City,Adequately immunized %,Exempt %,Conditionally enrolled %,Extended conditionally enrolled %,Out of compliance %,District/LEA,Grades,Address,Zip,Map,school_type
0,river rock school,lehi,89.7,10.3,0.0,0.0,0.0,Alpine District,Pre - 6,520 North 1700 West,84043,"geo:40.3937097,-111.8764976",Public
1,springside school,saratoga springs,82.9,13.7,0.9,0.9,1.7,Alpine District,Pre - 6,694 South Highpoint Drive,84045,"geo:40.3494704,-111.9152738",Public
2,american preparatory academy,draper,92.0,7.0,1.0,0.0,0.0,American Preparatory Academy,K - 6,12892 S PONY EXPRESS RD,84020,"geo:40.517489,-111.891825",Charter
3,ascent academies of utah lehi,lehi,87.0,13.0,0.0,0.0,0.0,Ascent Academies of Utah,K - 9,2199 W 900 N,84043,"geo:40.3986691,-111.8870765",Charter
4,birch creek school,smithfield,93.0,5.3,0.9,0.0,0.9,Cache District,Pre - 6,675 W 220 N,84335,"geo:41.842084,-111.852014",Public
...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,silver lake elementary,eagle mountain,84.5,15.5,0.0,0.0,0.0,Alpine District,Pre - 6,5069 Golden Eagle Road,84005,"geo:40.350111,-111.96156",Public
514,sunburst school,layton,90.2,7.3,0.0,1.6,0.8,Davis District,Pre - 6,2504 W Sunburst Drive,84041,"geo:41.06016,-112.01109",Public
515,trailside elementary,vineyard,86.1,7.9,0.0,6.0,0.0,Alpine District,Pre - 6,452 N Vineyard Loop Road,84058,"geo:40.30451,-111.74758",Public
516,twenty wells elementary,grantsville,94.0,6.0,0.0,0.0,0.0,Tooele District,Pre - 6,636 E Nygreen,84029,"geo:40.5783,-112.43632",Public
517,utah peak academy,junction,50.0,45.0,2.5,0.0,2.5,Piute District,K - 12,PO Box 69,84740,"geo:38.245546,-112.221783",Public

In [160]:
immunizations.to_csv("immunizations.csv", index=False)