In [18]:
import sys
import pandas as pd
import seaborn

In [ ]:
vax_exemptions = pd.read_csv('school_vaccine_exemptions.csv')
elementary_directory = pd.read_csv('elementary_directory.csv', quotechar='"') 
#https://schools.utah.gov/schoolsdirectory

# Rename the first column (index 0)
vax_exemptions = vax_exemptions.rename(columns={vax_exemptions.columns[0]: 'School'})
# df = df.dropna(how='all')
vax_exemptions = vax_exemptions.dropna(how = 'all') # this didn't work lol

In [39]:
vax_exemptions

,School,City,Adequately immunized %,Exempt %,Conditionally enrolled %,Extended conditionally enrolled %,Out of compliance %
1,river rock school,lehi,89.7,10.3,0.0,0.0,0.0
2,springside school,saratoga springs,82.9,13.7,0.9,0.9,1.7
3,american preparatory academy accelerated school,west valley city,94.2,3.5,0.0,2.3,0.0
4,american preparatory academy,draper,92.0,7.0,1.0,0.0,0.0
5,american preparatory academy salem,salem,74.6,25.4,0.0,0.0,0.0
...,...,...,...,...,...,...,...
692,island view school,west point,91.0,7.2,0.0,0.9,0.9
694,utah peak academy,junction,50.0,45.0,2.5,0.0,2.5
695,wallace stegner academy kearns,west valley city,95.9,4.1,0.0,0.0,0.0
696,haven bay,west haven,89.8,8.5,0.0,1.7,0.0
697,american principles academy,cedar,54.2,37.5,0.0,8.3,0.0

In [40]:
def normalize_str(s):
    return s.str.strip().str.lower()

for col in ['School', 'City']:
    vax_exemptions[col] = normalize_str(vax_exemptions[col])
    elementary_directory[col] = normalize_str(elementary_directory[col])

merged_df = pd.merge(vax_exemptions, elementary_directory, on=['School', 'City'], how='left')

In [41]:
merged_df

,School,City,Adequately immunized %,Exempt %,Conditionally enrolled %,Extended conditionally enrolled %,Out of compliance %,District/LEA,District #,School #,...,Link,Stats,Phone,Fax,Chartered By,Opened,Closed,Principal/Director,Principal Name,Principal Email
0,river rock school,lehi,89.7,10.3,0.0,0.0,0.0,Alpine District,01,201.0,...,www.alpineschools.org,https://datagateway.schools.utah.gov/Schools/0...,801-610-8731,801-768-7060,NaN,2015.0,2027.0,Principal,Brian Ridge,bridge@alpinedistrict.org
1,springside school,saratoga springs,82.9,13.7,0.9,0.9,1.7,Alpine District,01,202.0,...,alpineschools.org,https://datagateway.schools.utah.gov/Schools/0...,801-610-8732,801-854-5505,NaN,2016.0,2027.0,Principal,John Labare III,jlabare@alpinedistrict.org
2,american preparatory academy accelerated school,west valley city,94.2,3.5,0.0,2.3,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,american preparatory academy,draper,92.0,7.0,1.0,0.0,0.0,American Preparatory Academy,74,100.0,...,http://www.americanprep.org,https://datagateway.schools.utah.gov/Schools/7...,801-553-8500,801-576-9300,State Charter School Board (SCSB),2003.0,NaN,Superintendent,Carolyn Sharette,jbrennan@apamail.org
4,american preparatory academy salem,salem,74.6,25.4,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,island view school,west point,91.0,7.2,0.0,0.9,0.9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,utah peak academy,junction,50.0,45.0,2.5,0.0,2.5,Piute District,23,100.0,...,piutek12.org,https://datagateway.schools.utah.gov/Schools/2...,435-577-1202,NaN,NaN,2024.0,NaN,Principal,NaN,koby.willis@piutek12.org
631,wallace stegner academy kearns,west valley city,95.9,4.1,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
632,haven bay,west haven,89.8,8.5,0.0,1.7,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
633,american principles academy,cedar,54.2,37.5,0.0,8.3,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
immunizations = merged_df.drop_duplicates(subset = ['School', 'City'])
immunizations = immunizations.drop(columns = ['Phone', 'Fax', 'Principal Name', 'Conditionally enrolled %', 'Extended conditionally enrolled %', 'Out of compliance %', 'District #', 'School #', 'Grades', 'Link', 'Stats', 'Chartered By', 'Opened', 'Closed', 'Principal/Director', 'Principal Email'])
immunizations = immunizations.reset_index(drop = True)

In [49]:
immunizations

,School,City,Adequately immunized %,Exempt %,District/LEA,Private,Charter,T-I Prev.,T-I Curr.,Address,Zip,Map
0,river rock school,lehi,89.7,10.3,Alpine District,Public,NaN,NaN,NaN,520 North 1700 West,84043,"geo:40.3937097,-111.8764976"
1,springside school,saratoga springs,82.9,13.7,Alpine District,Public,NaN,NaN,NaN,694 South Highpoint Drive,84045,"geo:40.3494704,-111.9152738"
2,american preparatory academy accelerated school,west valley city,94.2,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,american preparatory academy,draper,92.0,7.0,American Preparatory Academy,Public,Charter,NaN,NaN,12892 S PONY EXPRESS RD,84020,"geo:40.517489,-111.891825"
4,american preparatory academy salem,salem,74.6,25.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
629,island view school,west point,91.0,7.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,utah peak academy,junction,50.0,45.0,Piute District,Public,NaN,NaN,NaN,PO Box 69,84740,"geo:38.245546,-112.221783"
631,wallace stegner academy kearns,west valley city,95.9,4.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
632,haven bay,west haven,89.8,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
633,american principles academy,cedar,54.2,37.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
immunizations['Private'] = immunizations['Private'].isna().astype(int)
immunizations['Charter'] = immunizations['Charter'].notna().astype(int)
immunizations['Public'] = ((immunizations['Private'] == 0) & (immunizations['Charter'] == 0)).astype(int)

In [51]:
def classify_school(row):
    if row['Charter'] == 0 and row['Public'] == 1:
        return 'Private'
    elif row['Charter'] == 1 and row['Private'] == 0:
        return 'Public Charter'
    elif row['Charter'] == 1 and row['Private'] == 1:
        return 'Private Charter'
    else:
        return 'Public'
    

immunizations['school_type'] = immunizations.apply(classify_school, axis=1)

print(immunizations.loc[immunizations['school_type'] == 'Public Charter', 'School'])

3                           american preparatory academy
5                          ascent academies of utah lehi
16                            franklin discovery academy
21                              greenwood charter school
22                         hawthorn academy south jordan
32                                       scholar academy
42                               wallace stegner academy
43                        wasatch waldorf charter school
234                                   timpanogos academy
251                                        thomas edison
258                                 wasatch peak academy
261                               odyssey charter school
270                                      ranches academy
278                                       reagan academy
296                        edith bowen laboratory school
301                               dual immersion academy
302                                   canyon rim academy
322                                     guadalupe school
325                                       open classroom
343                             maria montessori academy
345                            bear river charter school
348                       weilenmann school of discovery
351                                 noah webster academy
354                                        channing hall
359                                         vista school
365                                        endeavor hall
367                             good foundations academy
495                                       valley academy
499                             mountain view montessori
511                          leadership learning academy
512                                    jefferson academy
513                     mountain west montessori academy
516                             pacific heritage academy
520                 ascent academies of utah west jordan
526                            george washington academy
558                                   bonneville academy
566    the center for creativity innovation and disco...
571                  ascent academies of utah farmington
572                                 canyon grove academy
574                                     esperanza school
575                          gateway preparatory academy
577          promontory school of expeditionary learning
580                        soldier hollow charter school
582                                       voyage academy
587                      ignite entrepreneurship academy
590                              treeside charter school
594                               advantage arts academy
596            ascent academies of utah saratoga springs
598                             bridge elementary school
612                        monticello academy west point
613                             mountain sunrise academy
Name: School, dtype: str

In [54]:
print(immunizations.columns)
# immunizations = merged_df.drop_duplicates(subset = ['School'])
immunizations = immunizations.drop(columns = ['T-I Prev.', 'T-I Curr.', 'Private', 'Charter', 'Public'])
# immunizations = immunizations.reset_index(drop = True)
# immunizations.to_csv("immunizations.csv", index=False)

Index(['School', 'City', 'Adequately immunized %', 'Exempt %', 'District/LEA',
       'Private', 'Charter', 'T-I Prev.', 'T-I Curr.', 'Address', 'Zip', 'Map',
       'Public', 'school_type'],
      dtype='str')

In [55]:
immunizations

,School,City,Adequately immunized %,Exempt %,District/LEA,Address,Zip,Map,school_type
0,river rock school,lehi,89.7,10.3,Alpine District,520 North 1700 West,84043,"geo:40.3937097,-111.8764976",Private
1,springside school,saratoga springs,82.9,13.7,Alpine District,694 South Highpoint Drive,84045,"geo:40.3494704,-111.9152738",Private
2,american preparatory academy accelerated school,west valley city,94.2,3.5,NaN,NaN,NaN,NaN,Public
3,american preparatory academy,draper,92.0,7.0,American Preparatory Academy,12892 S PONY EXPRESS RD,84020,"geo:40.517489,-111.891825",Public Charter
4,american preparatory academy salem,salem,74.6,25.4,NaN,NaN,NaN,NaN,Public
...,...,...,...,...,...,...,...,...,...
629,island view school,west point,91.0,7.2,NaN,NaN,NaN,NaN,Public
630,utah peak academy,junction,50.0,45.0,Piute District,PO Box 69,84740,"geo:38.245546,-112.221783",Private
631,wallace stegner academy kearns,west valley city,95.9,4.1,NaN,NaN,NaN,NaN,Public
632,haven bay,west haven,89.8,8.5,NaN,NaN,NaN,NaN,Public
633,american principles academy,cedar,54.2,37.5,NaN,NaN,NaN,NaN,Public

In [56]:
immunizations.to_csv("immunizations.csv", index=False)